### ISSUE TITLE
what is it all about ?

### ISSUE THREAD

**Issue by sallespro** [substack/swarmlog#2]
sometimes i find difficult to keep up with the pace of innovation and the experiments you're going throught.
please let me know what you're up to here.

**Comment by substack** [comment]
You can create an append-only feed with hyperlog that gets shared with a swarm of peers, who will replicate with each other. The feed is signed with an ed25519 key, so only the original author can add documents to the feed. In this way, you can create infrastructure for sharing mutable feeds of data that scales without any servers.

**Comment by sallespro** [comment]
neat.
what about the swarm creation and the ed25519 choice ?
Em 07/02/2016, à(s) 22:52, James Halliday <notifications@github.com> escreveu:
